### ISSUE TITLE
Linux binary precompile glibc requirement is too high for some popular distros.

### ISSUE THREAD

**Issue by jordanmack** [nervosnetwork/capsule#101]
Trying to use the precompiled binary gives the following errors on some popular Linux distros:

OpenSSL3
```
./capsule: error while loading shared libraries: libssl.so.3: cannot open shared object file: No such file or directory
```

GLIBC
```
./capsule: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./capsule)
./capsule: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./capsule)
./capsule: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./capsule)
```

OpenSSL can probably be ignored since OpenSSL 1.1.1 will hit EOL this year. However, Glibc cannot easily be updated and is still being used in several popular distros. I did some research and found the following distros are affected:

MX Linux v21.3 (newest)
Debian 11 (newest)
Ubuntu 20.04 LTS (supported until 2025)

MX Linux is currently the most popular Linux distro according to DistroWatch. Debian 11 serves as a base for many other distros. Ubuntu 20.04 LTS is the previous LTS version with support until 2025.

Building against Glibc 2.31 should fix the issue with the OSs listed above. OpenSSL can probably be ignored since it's near EOL, or static linking could be considered.

**Comment by blckngm** [comment]
We can build on ubuntu 20.04.

If we remove the deployment feature, openssl won't be necessary.

**Comment by jjyr** [comment]
https://github.com/nervosnetwork/capsule/pull/102

Building binaries on ubuntu-20.04 may fix this.

**Comment by blckngm** [comment]
So the published binary for the next version will be compatible with ubuntu 20.04.

But it won't be compatible with ubuntu 22.04? (Ubuntu 22.04 doesn't have openssl 1.1?)

What do we want to do about openssl? We can link it statically, or use rustls, or just remove the deployment feature.

**Comment by jjyr** [comment]
Static link with openssl in Linux release #107

**Comment by jjyr** [comment]
https://github.com/nervosnetwork/capsule/releases/tag/v0.9.2 should fix this issue.

@jordanmack Can you try the capsule v0.9.2 binary on your machine?

**Comment by blckngm** [comment]
Closing. Please reopen if 0.9.2 still has this problem.
