### ISSUE TITLE
Bytes Inconsistent Length

### ISSUE THREAD

**Issue by phroi** [nervosnetwork/capsule#108]
Executing [these tests](https://github.com/phroi/capsule_bytes_inconsistent_length) on `Capsule 0.9.0` with `rustc 1.63.0` exhibits the following behavior.

From [Lumos JavaScript](https://github.com/phroi/capsule_bytes_inconsistent_length/blob/master/1_reproduce_error/index.js#L112):

``` javascript
{
    codeHash: DATA_FILE_HASH_1,
    hashType: "data1",
    args: "0x"
};
```

But then from the [rust code](https://github.com/phroi/capsule_bytes_inconsistent_length/blob/master/len_error_script/contracts/len_error_script/src/entry.rs#L13):

``` rust
debug!("script.args().len(): {:#?}", script.args().len());
debug!("script.args().as_slice().len(): {:#?}", script.args().as_slice().len());
```

And the output is:

``` bash
script.args().len(): 0
script.args().as_slice().len(): 4
```
Keep up the Great work :muscle:
Phroi

**Comment by blckngm** [comment]
This is molecule packed [Bytes](https://docs.rs/ckb-standalone-types/latest/ckb_standalone_types/packed/struct.Bytes.html) vs molecule::bytes::Bytes. A packed bytes starts with the length of its content in little endian u32.

It's an unfortunate naming conflict and a common source of confusion or bugs. I think we should probably rename packed bytes to PackedBytes or MolBytes and add some warning/notes on its (and its Reader's) `as_bytes`/`as_slice` method.

**Comment by blckngm** [comment]
You should mostly always use `raw_data` or `unpack` on a packed bytes.

**Comment by phroi** [comment]
Thanks @sopium, now makes much more sense!! Would you mind if I ask more questions here?

Say I have two instances of [ckb_standalone_types::packed::Script](https://docs.rs/ckb-standalone-types/latest/ckb_standalone_types/packed/struct.Script.html):

1) It's **safe** to compare them by using `script1.as_slice() == script2.as_slice()`?

(_If I understand correctly, this is safe but just compares their molecule representation._)

2) Is there a **short** more **idiomatic** way to achieve this equality check?

(_One of the two scripts is queried from the Blockchain, so its script hash is available, the other one is constructed using ScriptBuilder, so its script hash is not available._)

**Comment by blckngm** [comment]
Comparing by `script1.as_slice() == script2.as_slice()` is fine.

Unless you already have hashes of both scripts, comparing the slices should be more efficient (than calculating the hash just for comparison).

**Comment by phroi** [comment]
Very appreciated, thanks :pray:

**Comment by blckngm** [comment]
You are welcome. You can open an issue at ckb or molecule if you have some suggestions or thoughts on how the two Bytes types and the `as_slice`/`as_bytes` methods can be better documented.
