### ISSUE TITLE
A difference between capsule-env and real ckb-vm

### ISSUE THREAD

**Issue by cosinlink** [nervosnetwork/capsule#11]
**Describe the bug**
in capsule, I can use the code 'load_cell_data_hash(0, Source::Input)?' to get the hash of CellData from tx.inputs[0],
however,  I failed to get the hash of CellData from tx.inputs[0] by using the same code in ckb-vm.
Ckb-vm is not allowed user to get the CellDataHash from tx.inputs.

**Additional context**
I use the typescript contract by c to check if I can get the CellDataHash in ckb chain:
```
int main() {
  ckb_debug( "begin" );
  uint8_t buffer[1000];
  uint64_t len_data = 1;
  int ret_data = ckb_load_cell_data(buffer, &len_data, 0, 0, CKB_SOURCE_INPUT);
  if (ret_data != CKB_SUCCESS) {
    return ret_data;
  }
  ckb_debug( "ckb_load_cell_data success" );
  // get data hash
  uint64_t len = BLAKE2B_BLOCK_SIZE;
  unsigned char data_hash[BLAKE2B_BLOCK_SIZE];
  int ret = ckb_load_cell_by_field( data_hash,  &len, 0, 0, CKB_SOURCE_INPUT, CKB_CELL_FIELD_DATA_HASH);
  if (ret != CKB_SUCCESS) {
    return ret;
  }
  ckb_debug( "SUCCESS CKB_SOURCE_INPUT Datahash!" );
  return 0;
}
```
It failed.

* Capsule 0.0.0-pre.1
* ckb-cli 0.33.0 (2a70986 2020-06-15)%

**Comment by jjyr** [comment]
* What is your mean by using the same code in `ckb-vm`? Deploy & Run the contract on a real chain?
* What is your expected behavior?
* If your script failed, what is the returned error code?

**Comment by cosinlink** [comment]
- what I mean is `in ckb-vm` == `Deploy & Run the contract on a real chain`
- `expected behavior` 
  - In capsule,  the contract code `load_cell_data_hash(index, Source::Input)`  should return Err(_) under any circumstances;
  - For the consistency of the contract code between real chain and capsule
- `Script(ValidationFailur(2))`
  - I'm not sure if this is what ckb developers expect

**Comment by xxuejie** [comment]
> In capsule, the contract code load_cell_data_hash(index, Source::Input) should return Err(_) under any circumstances;

I don't really understand this, why `load_cell_data_hash` should return an error?
