### ISSUE TITLE
[Help Wanted] What's the best practices to setup the local development environment ro capsule project?

### ISSUE THREAD

**Issue by doitian** [nervosnetwork/capsule#110]
What's the best practices to setup the local development environment so that

- I can use IDE with rust-analyzer support to edit contracts and tests.
- I can use tools such as cargofmt, clippy on contracts and tests.

My current approach:

- Choose "nightly-2022-08-01" as the local toolchain.
- Exclude "tests" from the workspace as suggested by https://github.com/nervosnetwork/capsule/issues/85

This is not perfect, I still got errors like 

```
found duplicate lang item `oom`
the lang item is first defined in crate `std` (which `test` depends on)
first definition in `std` loaded from /home/gitpod/.rustup/toolchains/nightly-2022-08-01-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-c28e44e30a7ed831.rlib
second definition in the local crate (`...`)
```

But at least, I have a working rustfmt and rust-analyzer in the project.

I know I should use the target riscv64-unknown-elf-gcc instead of the host default target, but I don't know how to setup all the required packages.

**Comment by blckngm** [comment]
Have  you tried the latest develop branch? I have fixed rust-analyzer “duplicate lang item” errors by adding `cfg(test)`. Running `cargo clippy` or `cross clippy` is also supported.

**Comment by doitian** [comment]
I tried develop branch. Rust-analyzer is green and rustfmt works. 👍
