### ISSUE TITLE
[Question] How to calculate script hash from a Script instance?

### ISSUE THREAD

**Issue by phroi** [nervosnetwork/capsule#111]
As per title, I'm wondering: within a Rust L1 script, what's the most idiomatic way to calculate script hash from a Script instance?

I'm asking here since GitHub issues are SEO friendly and very likely in the future there will be other L1 developers wondering the same :wink:

Phroi

**Comment by blckngm** [comment]
Generally, just use a blake2b crate that supports no_std and calculate `blake2b(script.as_slice())` (with ckb output length and personalization).

It's also possible that you can load the script hash with a syscall, if the script is the type/lock script of a cell referenced/created by the current tx, see
- https://docs.rs/ckb-std/latest/ckb_std/high_level/fn.load_cell_lock_hash.html
- https://docs.rs/ckb-std/latest/ckb_std/high_level/fn.load_cell_type_hash.html
- https://docs.rs/ckb-std/latest/ckb_std/high_level/fn.look_for_dep_with_hash2.html

**Comment by phroi** [comment]
> It's also possible that you can load the script hash with a syscall,

If it was possible to load the hash, of course that would be the preferred choice :wink:

> Generally, just use a blake2b crate that supports no_std and calculate blake2b(script.as_slice()) (with ckb output length and personalization).

A valid `no_std` blake2b crate is [blake2b-ref](https://docs.rs/blake2b-ref/latest/blake2b_ref/index.html) and from the [Transaction Structure RFC](https://github.com/nervosnetwork/rfcs/blob/master/rfcs/0022-transaction-structure/0022-transaction-structure.md#crypto-primitives) the blake2b parameters are:
> - output digest size: 32
> - personalization: ckb-default-hash

@sopium would you agree on the following implementation?

```
use blake2b_ref::Blake2bBuilder;

fn script_hash(script: &Script) -> [u8; 32] {
    let mut output = [0u8; 32];
    let mut blake2b = Blake2bBuilder::new(32).personal(b"ckb-default-hash").build();
    blake2b.update(script.as_slice());
    blake2b.finalize(&mut output);
    output
}
```

**Comment by blckngm** [comment]
Yes, that's right.

**Comment by phroi** [comment]
Perfect, thanks a lot!! :pray:
