### ISSUE TITLE
Suggestion: Some console feedback when using 'capsule deploy'

### ISSUE THREAD

**Issue by tspoff** [nervosnetwork/capsule#12]
Currently, the console has no output while deploy is happening, which can take some time. It does nothing until the script is deployed, or an error occurs. I think it would be nice to give the user some feedback as to what is happening. 
![image](https://user-images.githubusercontent.com/5606917/91115117-1c4f8600-e64f-11ea-93d2-f6d23654b300.png)

**Comment by jjyr** [comment]
During the deployment, several txs will be sent to the node; I think we can add some feedback on txs sending.

Like: 
```
(1/3) Sending tx 0x00000....000001 ... Done!
(2/3) Sending tx 0x00000....000002 ... Done!
(3/3) Sending tx 0x00000....000003 ...
```

**Comment by tspoff** [comment]
Sounds perfect to me!

**Comment by jjyr** [comment]
https://github.com/nervosnetwork/capsule/commit/d9e4f479224a9c234ccb0428493f69c30a25882a
