### ISSUE TITLE
long ckt address report error: 'parse address: "invalid checksum"

### ISSUE THREAD

**Issue by wenyuanhust** [nervosnetwork/capsule#121]
**Describe the bug**
For long ckt address, capsule returns with error: parse address: "invalid checksum

**Screenshots**
Here is the command and error return
> capsule deploy --address ckt1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsqtp5rgl5262g5m2w7r9n4wc0wywsgvgk9cwc2mu8
thread 'main' panicked at 'parse address: "invalid checksum"', /root/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/ckb-capsule-0.10.0/src/bin/capsule.rs:378:48
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

If I change the long address to short address ckt1qyqxrgx3lg4553fk5auxt82as7ugaqsc3vtszxgefk. The error disappered.

**Additional context**
Capsule 0.10.0
ckb-cli    installed v1.4.0 (required v1.2.0)

**Comment by blckngm** [comment]
Proposal:

* For 0.10 next release and README / wiki / docs, add a warning that capsule deploy is deprecated in favor of ckb-cli deploy
* For 0.11, remove capsule deploy or make it a thin wrapper of ckb-cli deploy

WDYT?

**Comment by blckngm** [comment]
This issue per se shouldn't be too hard to fix, I'll fix it for 0.10.
