### ISSUE TITLE
Executing `new-contract` with the `--template` flag without an argument is successful.

### ISSUE THREAD

**Issue by jordanmack** [nervosnetwork/capsule#19]
Executing `new-contract` with the `--template` flag without an argument is successful, but an error should be presented.

```
username@dev1:~/dev$ capsule new-contract test1 --template
New contract "test1"
     Created binary (application) `test1` package
Rewrite Cargo.toml
Rewrite ckb_capsule.toml
Done
```

Capsule Version: `Capsule 0.4.2 dcfac5b`

**Comment by TheWaWaR** [comment]
Fixed in https://github.com/nervosnetwork/capsule/commit/2c8d9cb9023e61e8b40057dcad63ba7e42db4329

Now the argument specification is:
```
--template <template>    language template [default: rust]  [possible values: rust, c, c-sharedlib]
```
