### ISSUE TITLE
Suggestion: Add subcommands to delete and rename contracts.

### ISSUE THREAD

**Issue by jordanmack** [nervosnetwork/capsule#20]
It would be beneficial to have commands to delete and rename contracts after creation.

Capsule Version: `Capsule 0.4.2 dcfac5b`

**Comment by jjyr** [comment]
Rename and delete a Rust contract is easy because rust contracts are good structured, but c contracts usually rely on users customized build instructions; we can't clean it up. I suggest users need to delete generated files manually.
