### ISSUE TITLE
LLVM ERROR: Incomplete scavenging after 2nd pass

### ISSUE THREAD

**Issue by jjyr** [nervosnetwork/capsule#21]
**Describe the bug**

In some projects, the `capsule build --release` will raise this error.

https://github.com/jordanmack/nervos-ckb-nft/commit/f38598cdb05a92e3fdca8385c418058b676be35c

**Screenshots**
```
jjy@LAPTOP-BRD86RAC:~/workspace/nervos-ckb-nft$ capsule build --name nft --release
Building contract nft
   Compiling nft v0.1.0 (/code/contracts/nft)
LLVM ERROR: Incomplete scavenging after 2nd pass
error: could not compile `nft`

To learn more, run the command again with --verbose.
error: docker container exit with code Some(101)
```

**Additional context**

* `capsule --version` `Capsule 0.4.1`

-------------

**Solution**

This supposed to be an upstream issue, to edit the `Cargo.toml` `lto=false` can get around this in capsule projects.

**Comment by xxuejie** [comment]
Is this something we can file a bug report at Rust or even LLVM side?

**Comment by jjyr** [comment]
Sure, I'll try to reproduce it with a minimal example.

**Comment by blckngm** [comment]
Closing for now. Feel to to reopen if the problem still exists.
