### ISSUE TITLE
Compiling failed on MacOS 10.15

### ISSUE THREAD

**Issue by XuJiandong** [nervosnetwork/capsule#25]
**Describe the bug**
After installing capsule 0.4.4, using:

```
# check environment
capsule check

# create project
capsule new my-demo
cd my-demo
capsule build
capsule test

```

**Screenshots**
**Additional context**
Capsule 0.4.4 87bd895, it reports very long error, a snippets like this:
```txt
error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m64" "-Wl,--eh-frame-hdr"

  ........

  = note: collect2: fatal error: ld terminated with signal 9 [Killed]
          compilation terminated.
```
I think it might be the problem of OOM of LLVM, like this:
https://stackoverflow.com/questions/46259776/collect2-fatal-error-ld-terminated-with-signal-9-killed

The same problem is encountered by using Rust in docker without capsule (using capsule's docker container).

**Comment by TheWaWaR** [comment]
Tested with your instructions on `macOS 10.15.7`,  `Capsule 0.4.6` works just fine.
