### ISSUE TITLE
`capsule build` hangs on M1 Mac

### ISSUE THREAD

**Issue by cryptowen** [nervosnetwork/capsule#48]
**Describe the bug**
`capsule build` hangs on M1 Mac.

**Screenshots**
If applicable, add screenshots to help explain your problem. (The command and the output)

<img width="1496" alt="CleanShot 2021-12-27 at 11 19 21@2x" src="https://user-images.githubusercontent.com/1630721/147430949-f26cc651-36ec-4c0c-bee8-6677d573dfa7.png">

It just stopped here for more than 15 mins.

**Additional context**
```
/tmp/capsule
🕙 11:03:07 ❯ capsule new my-demo

New project "my-demo"
Created file "capsule.toml"
Created file "deployment.toml"
Created file "README.md"
Created file "Cargo.toml"
Created file ".gitignore"
Initialized empty Git repository in /private/tmp/capsule/my-demo/.git/
Created "/private/tmp/capsule/my-demo"
Created tests
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
     Created library `tests` package
New contract "my-demo"
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
     Created binary (application) `my-demo` package
Rewrite Cargo.toml
Rewrite capsule.toml
Done

/tmp/capsule took 2s
🕙 11:03:13 ❯ cd my-demo

my-demo on  master [?] via 🦀 v1.59.0-nightly
🕙 11:03:20 ❯ capsule build
Building contract my-demo
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
    Updating crates.io index
   Compiling memchr v2.4.1
   Compiling cfg-if v1.0.0
   Compiling cc v1.0.72
   Compiling cty v0.2.2
   Compiling buddy-alloc v0.4.1
   Compiling molecule v0.7.2
   Compiling ckb-standalone-types v0.1.2
   Compiling cstr_core v0.2.4
```

Please post the following informations:

* Output of `capsule --version`
* Output of `ckb-cli --version`
* Rerun your command with ` RUST_BACKTRACE=1 RUST_LOG=capsule=trace` environment, then post the output as a file.

```
my-demo on  master [?] via 🦀 v1.59.0-nightly
🕙 11:18:23 ❯ capsule --version
Capsule 0.7.1

my-demo on  master [?] via 🦀 v1.59.0-nightly
🕙 11:18:27 ❯ ckb-cli --version
ckb-cli 0.35.0 (3875086 2020-08-11)%
```

**Comment by XuJiandong** [comment]
@joii2020 will look into it. We will fix it in PR: https://github.com/nervosnetwork/capsule/pull/47

**Comment by TheWaWaR** [comment]
Looks like required a `linux/arm64/v8` version of capsule docker. Will try to build one and test it on my M1 Mac machine.

**Comment by TheWaWaR** [comment]
Fixed in https://github.com/nervosnetwork/capsule/pull/49. Please try capsule `v0.7.2`.

If you encountered any further problems please comment to reopen this issue.
