### ISSUE TITLE
Report toolchain xxx is not installed

### ISSUE THREAD

**Issue by XuJiandong** [nervosnetwork/capsule#52]
**Describe the bug**
Build https://github.com/nervosnetwork/godwoken-scripts with 0.7.2:
❯ capsule --version
Capsule 0.7.2
❯ capsule build
Building contract state-validator
error: toolchain 'nightly-2021-08-16-x86_64-unknown-linux-gnu' is not installed
error: docker container exit with code Some(1)

The capsule.toml file: https://github.com/nervosnetwork/godwoken-scripts/blob/master/capsule.toml#L5
It might be the problem of the following:
```
[rust]
workspace_dir = "contracts"
toolchain = "nightly-2021-08-16"
```
The image should be download automatically.

**Screenshots**
If applicable, add screenshots to help explain your problem. (The command and the output)

**Additional context**
Please post the following informations:

* Output of `capsule --version`
* Output of `ckb-cli --version`
* Rerun your command with ` RUST_BACKTRACE=1 RUST_LOG=capsule=trace` environment, then post the output as a file.

**Comment by TheWaWaR** [comment]
I think the right way it stick the docker_image version:
https://github.com/nervosnetwork/godwoken-scripts/pull/103

**Comment by blckngm** [comment]
Problem already solved.

FWIW, using cross can help with similar problems in the future: #84
