### ISSUE TITLE
Proxy doesn't work

### ISSUE THREAD

**Issue by XuJiandong** [nervosnetwork/capsule#55]
**Describe the bug**
capsule new test
cd test; capsule build

```
❯ capsule build
Building contract test2
    Updating crates.io index
warning: spurious network error (2 tries remaining): [7] Couldn't connect to server (Failed to connect to 127.0.0.1 port 7070 after 0 ms: Connection refused); class=Net (12)
warning: spurious network error (1 tries remaining): [7] Couldn't connect to server (Failed to connect to 127.0.0.1 port 7070 after 0 ms: Connection refused); class=Net (12)
error: failed to get `ckb-testtool` as a dependency of package `tests v0.1.0 (/code/tests)`

```

Note: need to purge cargo package cache in docker first. Otherwise, it will not use network.

**Screenshots**
If applicable, add screenshots to help explain your problem. (The command and the output)

**Additional context**
Please post the following informations:

* Output of `capsule --version`
* Output of `ckb-cli --version`
* Rerun your command with ` RUST_BACKTRACE=1 RUST_LOG=capsule=trace` environment, then post the output as a file.

**Comment by TheWaWaR** [comment]
Fixed in https://github.com/nervosnetwork/capsule/pull/56
