### ISSUE TITLE
Possibly wrong argc/argv

### ISSUE THREAD

**Issue by blckngm** [nervosnetwork/capsule#72]
Rust contracts built by `capsule build` (esp. in non-release build) may not get the correct argc and argv arguments because the compiler may insert function prologue before our assembly code in `_start` and change the `sp` register.

One possible solution is to mark the `_start` function [`#[naked]`](https://github.com/rust-lang/rfcs/blob/master/text/1201-naked-fns.md).

Or the `_start` function can be written in pure assembly and linked with rust code.

(By the way the `program_entry` function should use `extern "C"` so that it has a defined calling convention.)

**Comment by blckngm** [comment]
```
#[no_mangle]
#[naked]
pub unsafe extern "C" fn _start() -> ! {
    core::arch::asm!(
        "lw a0, 0(sp)",
        "addi a1, sp, 8",
        "call main",
        "li a7, 93",
        "ecall",
        options(noreturn)
    );
}

#[no_mangle]
extern "C" fn main(_argc: u64, _argv: *const *const u8) -> i8 {
    _argc as i8
}
```

**Comment by XuJiandong** [comment]
Use the code snippets below to work with `argc` and `argv`:

https://github.com/XuJiandong/rvv-testcases/blob/76944bc7a6d1e87c2e3d171f361881b92b1db9ff/cases/src/main.rs#L64-L81

**Comment by blckngm** [comment]
Global asm also works, and does not require any nightly features:

```
core::arch::global_asm!(
    ".global _start",
    "_start:",
    "lw a0, 0(sp)",
    "addi a1, sp, 8",
    "call main",
    "li a7, 93",
    "ecall",
);
```
