### ISSUE TITLE
Bug: Capsule v0.8.0 cannot be used with CKB-Cli v1.4.0

### ISSUE THREAD

**Issue by ashuralyk** [nervosnetwork/capsule#77]
**Describe the bug**
It seems `ckb-cli v1.4.0` needs to use option `--wait-for-sync` for `rpc` subcommand, but in capsule v0.8.0 there is no use that matches this pattern. So it makes the failure of deploying contract using capsule.

**Screenshots**
![image](https://user-images.githubusercontent.com/3871265/212674710-6859ca67-d390-42e9-8044-b24ce03d67fc.png)

**Additional context**
Please post the following informations:

* Output of `capsule --version` is `Capsule 0.8.0 e337a50`
* Output of `ckb-cli --version` is `ckb-cli 1.4.0 (7671237 2023-01-05)`
* Rerun your command with ` RUST_BACKTRACE=1 RUST_LOG=capsule=trace` environment, then post the output as a file.
![image](https://user-images.githubusercontent.com/3871265/212675582-2e701198-7515-40c5-a17e-b5c4ec9361a4.png)

**Comment by quake** [comment]
I think this bug has been resolved by https://github.com/nervosnetwork/capsule/pull/71 and released in capsule 0.9.0, could you upgrade the capsule and try again?

**Comment by blckngm** [comment]
Closing for now. Feel to to reopen if the problem still exists.
